# Generated by Django 4.2.1 on 2023-07-03 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('customer_id', models.IntegerField(validators=[django.core.validators.RegexValidator(message='ID should be a 9-digit number.', regex='^\\d{9}$')])),
            ],
        ),
    ]
