# Generated by Django 4.2.1 on 2023-07-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_book_remove_customer_id_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='book_id',
            new_name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='return_period',
            field=models.IntegerField(choices=[(1, 10), (2, 20), (3, 30)], default=1),
        ),
        migrations.AddField(
            model_name='rent',
            name='cust',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.customer'),
        ),
    ]
