# Generated by Django 4.2.1 on 2023-07-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_book_return_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='return_period',
            field=models.IntegerField(choices=[(1, '10 days'), (2, '20 days'), (3, '30 days')], default=2),
        ),
    ]
