# Generated by Django 4.2.1 on 2023-07-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_book_return_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='return_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
