# Generated by Django 4.2.1 on 2023-07-06 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rent_return_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='return_end_date',
        ),
        migrations.AlterField(
            model_name='rent',
            name='return_start_date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 7, 6, 14, 43, 9, 443185, tzinfo=datetime.timezone.utc)),
        ),
    ]
