# Generated by Django 4.2.1 on 2023-07-06 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_rent_return_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='return_start_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
