# Generated by Django 4.2.1 on 2023-07-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_rent_return_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='return_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
