# Generated by Django 4.2.1 on 2023-07-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_rent_return_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
