# Generated by Django 4.2.1 on 2023-07-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_customer_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='lib',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.library'),
        ),
        migrations.AddField(
            model_name='customer',
            name='lib',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.library'),
        ),
        migrations.AddField(
            model_name='rent',
            name='lib',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.library'),
        ),
    ]
