# Generated by Django 4.2.1 on 2023-08-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_imgs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imgs',
            new_name='Img',
        ),
    ]
