# Generated by Django 4.2.1 on 2023-09-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_book_img_book_cover_img_delete_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(blank=True, default='book_covers\\jru_cover.png', null=True, upload_to='book_covers/'),
        ),
    ]
